// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteConfig = XP.SiteConfig;

declare global {
  namespace XP {
    interface SiteConfig {
      /**
       * NextJS server URL
       */
      nextjsUrl?: string;

      /**
       * NextJS API token
       */
      nextjsToken?: string;
    }
  }
}
