// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type MenuItem = import("./menu-item").MenuItem

declare global {
  namespace XP {
    interface XData {
      "de-lyn-be"?: {
        "menu-item"?: MenuItem;
      }
    }
  }
}
