// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Container {
  /**
   * Größe Container
   */
  size: "sm" | "md" | "lg" | "xl";

  /**
   * Innenabstand oben/unter
   */
  padY: "0" | "0.5" | "1" | "1.5" | "2" | "2.5" | "3" | "3.5" | "4" | "5" | "6" | "7" | "8" | "9" | "10";
}
