// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MenuItem {
  /**
   * Show in menu?
   */
  menuItem: boolean;

  /**
   * Override menu name
   */
  menuName?: string;

  /**
   * Open in new window?
   */
  newWindow: boolean;

  /**
   * Menü-Icon
   */
  Icon?: Array<"one" | "two"> | "one" | "two";
}
