// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Book {
  /**
   * Hervorheben
   */
  featured: boolean;

  /**
   * Untertitel
   */
  subtitle?: string;

  /**
   * Klappentext
   */
  content?: string;

  /**
   * Serie
   */
  series?: string;

  /**
   * Folge
   */
  episode?: number;

  /**
   * ISBN 11 Nummer
   */
  ISBN11?: string;

  /**
   * ISBN 13 Nummer
   */
  ISBN13?: string;

  /**
   * Autor(in)
   */
  author?: string;

  /**
   * Erstveröffentlichung
   */
  published?: string;

  /**
   * Anzahl der Seiten
   */
  pages?: number;

  /**
   * Buchcover
   */
  cover?: string;

  /**
   * Darsteller
   */
  characters?: Array<string> | string;

  /**
   * Url auf Amazon
   */
  "amazon-url"?: string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "de_lyn_be_Book_Data";
}
