// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Character = import("./character").Character;
export type Book = import("./book").Book;

declare global {
  namespace XP {
    interface ContentTypes {
      "de.lyn.be:character": Character;
      "de.lyn.be:book": Book;
    }
  }
}
