// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Character {
  /**
   * Name
   */
  name?: string;

  /**
   * Profil
   */
  profile?: string;

  /**
   * Photo
   */
  photo?: string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "de_lyn_be_Character_Data";
}
