// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Banner {
  /**
   * Höhe in Prozent
   */
  height?: number;

  /**
   * Überschrift
   */
  header: string;

  /**
   * Text
   */
  teaser?: string;

  /**
   * aktivieren
   */
  hasTimer: boolean;

  /**
   * Zieldatum
   */
  timerDate?: string;

  /**
   * Text mit Datum anzeigen
   */
  hasText: boolean;

  /**
   * Text vor Datum
   */
  timerText?: string;

  /**
   * aktivieren
   */
  hasLink: boolean;

  /**
   * My ContentSelector
   */
  linkTarget?: string;

  /**
   * Beschriftung
   */
  linkText?: string;

  /**
   * Anzuzeigendes Bild
   */
  image?: string;

  /**
   * Bild in Schwarz-Weiss
   */
  grayscale: boolean;
}
