// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Banner {
  /**
   * Höhe in Prozent
   */
  height?: number;

  /**
   * Überschrift
   */
  header: string;

  /**
   * Text
   */
  teaser?: string;

  /**
   * Anzuzeigendes Bild
   */
  image?: string;
}
